# -*- coding: utf-8 -*-
"""Trulia_Real_Estate_Web_Scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tlZKuFuKFshgnT-SFy6QtianCv-qDlyD

# **IMPORT LIBRARIES**
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

"""# **HTTP Requests**

**Store URL**
"""

website='https://www.trulia.com/for_sale/San_Francisco,CA/37.66849,37.82258,-122.56718,-122.31189_xy/12_zm/'

"""**GET() Request**"""

response=requests.get(website)

"""**STATUS CODE**"""

response.status_code

"""**SOUP OBJECT**"""

soup=BeautifulSoup(response.content,'html.parser')
soup

"""### **RESULTS**

"""

result=soup.find_all('li',{'class':'SearchResultsList__WideCell-b7y9ki-2'})

len(result)

"""### **UPDATE Results**

Lets just want to target the elements which have the attribute 'data-testid'
"""

results_update=[]

for r in result:
  if r.has_attr('data-testid'):
    results_update.append(r)

len(results_update)    # Now only the 'data-testid' attribute lists have been added to results_update

results_update[0]

"""### **TARGET NECCESSARY DATA**"""

# STREET

results_update[0].find('div',{'data-testid':'property-street'}).get_text()

# REGION 

results_update[0].find('div',{'data-testid':'property-region'}).get_text()

# PRICE

results_update[0].find('div',{'data-testid':'property-price'}).get_text()

# BEDS_AVAILABLE

results_update[0].find('div',{'data-testid':'property-beds'}).get_text().replace("bd",'')

# BATHROOMS_AVAILABLE

results_update[0].find('div',{'data-testid':'property-baths'}).get_text().replace("ba",'')

# SQUARE FEET 

results_update[0].find('div',{'data-testid':'property-floorSpace'}).get_text().replace("sqft",'')

"""# **APPEND ALL RESULTS IN LISTS USING LIST COMPREHENSION**"""

streets=[result.find('div',{'data-testid':'property-street'}).get_text() for result in results_update]
# streets

regions=[result.find('div',{'data-testid':'property-region'}).get_text() for result in results_update]
#regions

pricing=[result.find('div',{'data-testid':'property-price'}).get_text() for result in results_update]
# pricing

bed=[result.find('div',{'data-testid':'property-beds'}).get_text().replace("bd",'') for result in results_update]
#bed

bathroom=[result.find('div',{'data-testid':'property-baths'}).get_text().replace("ba",'') for result in results_update]
#bathroom

# sqr_ft=[result.find('div',{'data-testid':'property-floorSpace'}).get_text().replace("sqft",'') for result in results_update]
# sqr_ft

real_estate=pd.DataFrame({'Street':streets,'Region':regions,'Price':pricing,'Bedrooms':bed,'Bathrooms':bathroom})
real_estate

real_estate.to_excel('Trulia_Real_Estate.xlsx',index=False)

